<%@ Page Title="" Language="C#" MasterPageFile="~/DashBoard.Master" AutoEventWireup="true" CodeBehind="Help.aspx.cs" Inherits="Get_Your_TA.Help" ClientIDMode="Static"%>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="Content/help.css" rel="stylesheet" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="mainPlaceHolder" runat="server">
    <div class="col-sm-12">
        <p class="headings"><b>Overview</b></p>
        <p>Get Your TA is a Desktop Application software Designed and Developed by LogiCode.</p>
        <p>The software focuses on generation of TA (Travelling allowance) bill and Tour Diary.</p>
        <p>Get your TA is mainly developed for the government servants of Maharashtra state, previously the
bill was generated manually which was very tedious task, this product generates the TA bill within
no time that too efficiently.</p>
        <p>Users just need to enter some values such as date, time, destination and vehicle type etc.</p>
        <p>Some values such as distance are auto generated by the software resulting in reduction of the tasks
of the user.</p>
    </div>

    <div class="col-sm-12">
        <p class="headings"><b>Advantages</b></p>
        <p>1. It is fast and efficient.</p>
        <p>2. It is very handy to use.</p>
        <p>3. It can generate an excel sheet of your TA bill & Tour Diary.</p>
        <p>4. It keeps a record in the tour diary.</p>
        <p>5. Support for Local Language (Marathi).</p>
    </div>
    <div class="col-sm-12">
        <p class="headings"><b>Help Document</b></p>
        <a href="Images/Help.pdf">Help.pdf</a>
    </div>
    
</asp:Content>
